version: "3"
services:
  golang:
    build: ./000_container
    # environment:
    #   TOKEN_KEY: ''
    volumes: 
      - golang:/go
      - ssh:/root/.ssh/
    stdin_open: true
    tty: true
volumes: 
  golang:
  ssh: