version: "3"
services:
  golang:
    build: ./000_container
    volumes: 
      - ./:/go/src/golang-examples
      - ccgc-extensions:/root/.vscode-server/extensions
      - ccgc-go-bin:/go/bin
    stdin_open: true
    tty: true
volumes: 
  ccgc-extensions:
  ccgc-go-bin:
